spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: c##a
    password: hieu
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8802
